#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v20
# autospec commit: a19cdc7
#
Name     : compat-abseil-cpp-rolling
Version  : 20240116.2
Release  : 11
URL      : https://github.com/abseil/abseil-cpp/archive/20240116.2/abseil-cpp-20240116.2.tar.gz
Source0  : https://github.com/abseil/abseil-cpp/archive/20240116.2/abseil-cpp-20240116.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: compat-abseil-cpp-rolling-lib = %{version}-%{release}
Requires: compat-abseil-cpp-rolling-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : glibc-dev
BuildRequires : googletest-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Workaround-dependency-failure.patch
Patch2: 0002-Drop-use-of-ctzs.patch

%description
# Abseil - C++ Common Libraries
The repository contains the Abseil C++ library code. Abseil is an open-source
collection of C++ code (compliant to C++14) designed to augment the C++
standard library.

%package lib
Summary: lib components for the compat-abseil-cpp-rolling package.
Group: Libraries
Requires: compat-abseil-cpp-rolling-license = %{version}-%{release}

%description lib
lib components for the compat-abseil-cpp-rolling package.


%package license
Summary: license components for the compat-abseil-cpp-rolling package.
Group: Default

%description license
license components for the compat-abseil-cpp-rolling package.


%prep
%setup -q -n abseil-cpp-20240116.2
cd %{_builddir}/abseil-cpp-20240116.2
%patch -P 1 -p1
%patch -P 2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1728434885
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DBUILD_SHARED_LIBS=ON \
-DBUILD_TESTING=ON \
-DABSL_BUILD_TEST_HELPERS=ON \
-DABSL_USE_EXTERNAL_GOOGLETEST=ON \
-DABSL_FIND_GOOGLETEST=ON  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1728434885
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-abseil-cpp-rolling
cp %{_builddir}/abseil-cpp-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/compat-abseil-cpp-rolling/77ca6ddbb42e1c1c589a0874f0ad28b7da4cccbb || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd
## Remove excluded files
rm -f %{buildroot}*/usr/include/absl/algorithm/algorithm.h
rm -f %{buildroot}*/usr/include/absl/algorithm/container.h
rm -f %{buildroot}*/usr/include/absl/base/attributes.h
rm -f %{buildroot}*/usr/include/absl/base/call_once.h
rm -f %{buildroot}*/usr/include/absl/base/casts.h
rm -f %{buildroot}*/usr/include/absl/base/config.h
rm -f %{buildroot}*/usr/include/absl/base/const_init.h
rm -f %{buildroot}*/usr/include/absl/base/dynamic_annotations.h
rm -f %{buildroot}*/usr/include/absl/base/internal/atomic_hook.h
rm -f %{buildroot}*/usr/include/absl/base/internal/atomic_hook_test_helper.h
rm -f %{buildroot}*/usr/include/absl/base/internal/cycleclock.h
rm -f %{buildroot}*/usr/include/absl/base/internal/cycleclock_config.h
rm -f %{buildroot}*/usr/include/absl/base/internal/direct_mmap.h
rm -f %{buildroot}*/usr/include/absl/base/internal/dynamic_annotations.h
rm -f %{buildroot}*/usr/include/absl/base/internal/endian.h
rm -f %{buildroot}*/usr/include/absl/base/internal/errno_saver.h
rm -f %{buildroot}*/usr/include/absl/base/internal/exception_safety_testing.h
rm -f %{buildroot}*/usr/include/absl/base/internal/exception_testing.h
rm -f %{buildroot}*/usr/include/absl/base/internal/fast_type_id.h
rm -f %{buildroot}*/usr/include/absl/base/internal/hide_ptr.h
rm -f %{buildroot}*/usr/include/absl/base/internal/identity.h
rm -f %{buildroot}*/usr/include/absl/base/internal/inline_variable.h
rm -f %{buildroot}*/usr/include/absl/base/internal/inline_variable_testing.h
rm -f %{buildroot}*/usr/include/absl/base/internal/invoke.h
rm -f %{buildroot}*/usr/include/absl/base/internal/low_level_alloc.h
rm -f %{buildroot}*/usr/include/absl/base/internal/low_level_scheduling.h
rm -f %{buildroot}*/usr/include/absl/base/internal/nullability_impl.h
rm -f %{buildroot}*/usr/include/absl/base/internal/per_thread_tls.h
rm -f %{buildroot}*/usr/include/absl/base/internal/pretty_function.h
rm -f %{buildroot}*/usr/include/absl/base/internal/raw_logging.h
rm -f %{buildroot}*/usr/include/absl/base/internal/scheduling_mode.h
rm -f %{buildroot}*/usr/include/absl/base/internal/scoped_set_env.h
rm -f %{buildroot}*/usr/include/absl/base/internal/spinlock.h
rm -f %{buildroot}*/usr/include/absl/base/internal/spinlock_akaros.inc
rm -f %{buildroot}*/usr/include/absl/base/internal/spinlock_linux.inc
rm -f %{buildroot}*/usr/include/absl/base/internal/spinlock_posix.inc
rm -f %{buildroot}*/usr/include/absl/base/internal/spinlock_wait.h
rm -f %{buildroot}*/usr/include/absl/base/internal/spinlock_win32.inc
rm -f %{buildroot}*/usr/include/absl/base/internal/strerror.h
rm -f %{buildroot}*/usr/include/absl/base/internal/sysinfo.h
rm -f %{buildroot}*/usr/include/absl/base/internal/thread_identity.h
rm -f %{buildroot}*/usr/include/absl/base/internal/throw_delegate.h
rm -f %{buildroot}*/usr/include/absl/base/internal/tsan_mutex_interface.h
rm -f %{buildroot}*/usr/include/absl/base/internal/unaligned_access.h
rm -f %{buildroot}*/usr/include/absl/base/internal/unscaledcycleclock.h
rm -f %{buildroot}*/usr/include/absl/base/internal/unscaledcycleclock_config.h
rm -f %{buildroot}*/usr/include/absl/base/log_severity.h
rm -f %{buildroot}*/usr/include/absl/base/macros.h
rm -f %{buildroot}*/usr/include/absl/base/no_destructor.h
rm -f %{buildroot}*/usr/include/absl/base/nullability.h
rm -f %{buildroot}*/usr/include/absl/base/optimization.h
rm -f %{buildroot}*/usr/include/absl/base/options.h
rm -f %{buildroot}*/usr/include/absl/base/policy_checks.h
rm -f %{buildroot}*/usr/include/absl/base/port.h
rm -f %{buildroot}*/usr/include/absl/base/prefetch.h
rm -f %{buildroot}*/usr/include/absl/base/thread_annotations.h
rm -f %{buildroot}*/usr/include/absl/cleanup/cleanup.h
rm -f %{buildroot}*/usr/include/absl/cleanup/internal/cleanup.h
rm -f %{buildroot}*/usr/include/absl/container/btree_map.h
rm -f %{buildroot}*/usr/include/absl/container/btree_set.h
rm -f %{buildroot}*/usr/include/absl/container/btree_test.h
rm -f %{buildroot}*/usr/include/absl/container/fixed_array.h
rm -f %{buildroot}*/usr/include/absl/container/flat_hash_map.h
rm -f %{buildroot}*/usr/include/absl/container/flat_hash_set.h
rm -f %{buildroot}*/usr/include/absl/container/inlined_vector.h
rm -f %{buildroot}*/usr/include/absl/container/internal/btree.h
rm -f %{buildroot}*/usr/include/absl/container/internal/btree_container.h
rm -f %{buildroot}*/usr/include/absl/container/internal/common.h
rm -f %{buildroot}*/usr/include/absl/container/internal/common_policy_traits.h
rm -f %{buildroot}*/usr/include/absl/container/internal/compressed_tuple.h
rm -f %{buildroot}*/usr/include/absl/container/internal/container_memory.h
rm -f %{buildroot}*/usr/include/absl/container/internal/hash_function_defaults.h
rm -f %{buildroot}*/usr/include/absl/container/internal/hash_generator_testing.h
rm -f %{buildroot}*/usr/include/absl/container/internal/hash_policy_testing.h
rm -f %{buildroot}*/usr/include/absl/container/internal/hash_policy_traits.h
rm -f %{buildroot}*/usr/include/absl/container/internal/hashtable_debug.h
rm -f %{buildroot}*/usr/include/absl/container/internal/hashtable_debug_hooks.h
rm -f %{buildroot}*/usr/include/absl/container/internal/hashtablez_sampler.h
rm -f %{buildroot}*/usr/include/absl/container/internal/inlined_vector.h
rm -f %{buildroot}*/usr/include/absl/container/internal/layout.h
rm -f %{buildroot}*/usr/include/absl/container/internal/node_slot_policy.h
rm -f %{buildroot}*/usr/include/absl/container/internal/raw_hash_map.h
rm -f %{buildroot}*/usr/include/absl/container/internal/raw_hash_set.h
rm -f %{buildroot}*/usr/include/absl/container/internal/test_allocator.h
rm -f %{buildroot}*/usr/include/absl/container/internal/test_instance_tracker.h
rm -f %{buildroot}*/usr/include/absl/container/internal/tracked.h
rm -f %{buildroot}*/usr/include/absl/container/internal/unordered_map_constructor_test.h
rm -f %{buildroot}*/usr/include/absl/container/internal/unordered_map_lookup_test.h
rm -f %{buildroot}*/usr/include/absl/container/internal/unordered_map_members_test.h
rm -f %{buildroot}*/usr/include/absl/container/internal/unordered_map_modifiers_test.h
rm -f %{buildroot}*/usr/include/absl/container/internal/unordered_set_constructor_test.h
rm -f %{buildroot}*/usr/include/absl/container/internal/unordered_set_lookup_test.h
rm -f %{buildroot}*/usr/include/absl/container/internal/unordered_set_members_test.h
rm -f %{buildroot}*/usr/include/absl/container/internal/unordered_set_modifiers_test.h
rm -f %{buildroot}*/usr/include/absl/container/node_hash_map.h
rm -f %{buildroot}*/usr/include/absl/container/node_hash_set.h
rm -f %{buildroot}*/usr/include/absl/crc/crc32c.h
rm -f %{buildroot}*/usr/include/absl/crc/internal/cpu_detect.h
rm -f %{buildroot}*/usr/include/absl/crc/internal/crc.h
rm -f %{buildroot}*/usr/include/absl/crc/internal/crc32_x86_arm_combined_simd.h
rm -f %{buildroot}*/usr/include/absl/crc/internal/crc32c.h
rm -f %{buildroot}*/usr/include/absl/crc/internal/crc32c_inline.h
rm -f %{buildroot}*/usr/include/absl/crc/internal/crc_cord_state.h
rm -f %{buildroot}*/usr/include/absl/crc/internal/crc_internal.h
rm -f %{buildroot}*/usr/include/absl/crc/internal/crc_memcpy.h
rm -f %{buildroot}*/usr/include/absl/crc/internal/non_temporal_arm_intrinsics.h
rm -f %{buildroot}*/usr/include/absl/crc/internal/non_temporal_memcpy.h
rm -f %{buildroot}*/usr/include/absl/debugging/failure_signal_handler.h
rm -f %{buildroot}*/usr/include/absl/debugging/internal/address_is_readable.h
rm -f %{buildroot}*/usr/include/absl/debugging/internal/demangle.h
rm -f %{buildroot}*/usr/include/absl/debugging/internal/elf_mem_image.h
rm -f %{buildroot}*/usr/include/absl/debugging/internal/examine_stack.h
rm -f %{buildroot}*/usr/include/absl/debugging/internal/stack_consumption.h
rm -f %{buildroot}*/usr/include/absl/debugging/internal/stacktrace_aarch64-inl.inc
rm -f %{buildroot}*/usr/include/absl/debugging/internal/stacktrace_arm-inl.inc
rm -f %{buildroot}*/usr/include/absl/debugging/internal/stacktrace_config.h
rm -f %{buildroot}*/usr/include/absl/debugging/internal/stacktrace_emscripten-inl.inc
rm -f %{buildroot}*/usr/include/absl/debugging/internal/stacktrace_generic-inl.inc
rm -f %{buildroot}*/usr/include/absl/debugging/internal/stacktrace_powerpc-inl.inc
rm -f %{buildroot}*/usr/include/absl/debugging/internal/stacktrace_riscv-inl.inc
rm -f %{buildroot}*/usr/include/absl/debugging/internal/stacktrace_unimplemented-inl.inc
rm -f %{buildroot}*/usr/include/absl/debugging/internal/stacktrace_win32-inl.inc
rm -f %{buildroot}*/usr/include/absl/debugging/internal/stacktrace_x86-inl.inc
rm -f %{buildroot}*/usr/include/absl/debugging/internal/symbolize.h
rm -f %{buildroot}*/usr/include/absl/debugging/internal/vdso_support.h
rm -f %{buildroot}*/usr/include/absl/debugging/leak_check.h
rm -f %{buildroot}*/usr/include/absl/debugging/stacktrace.h
rm -f %{buildroot}*/usr/include/absl/debugging/symbolize.h
rm -f %{buildroot}*/usr/include/absl/debugging/symbolize_darwin.inc
rm -f %{buildroot}*/usr/include/absl/debugging/symbolize_elf.inc
rm -f %{buildroot}*/usr/include/absl/debugging/symbolize_emscripten.inc
rm -f %{buildroot}*/usr/include/absl/debugging/symbolize_unimplemented.inc
rm -f %{buildroot}*/usr/include/absl/debugging/symbolize_win32.inc
rm -f %{buildroot}*/usr/include/absl/flags/commandlineflag.h
rm -f %{buildroot}*/usr/include/absl/flags/config.h
rm -f %{buildroot}*/usr/include/absl/flags/declare.h
rm -f %{buildroot}*/usr/include/absl/flags/flag.h
rm -f %{buildroot}*/usr/include/absl/flags/internal/commandlineflag.h
rm -f %{buildroot}*/usr/include/absl/flags/internal/flag.h
rm -f %{buildroot}*/usr/include/absl/flags/internal/parse.h
rm -f %{buildroot}*/usr/include/absl/flags/internal/path_util.h
rm -f %{buildroot}*/usr/include/absl/flags/internal/private_handle_accessor.h
rm -f %{buildroot}*/usr/include/absl/flags/internal/program_name.h
rm -f %{buildroot}*/usr/include/absl/flags/internal/registry.h
rm -f %{buildroot}*/usr/include/absl/flags/internal/sequence_lock.h
rm -f %{buildroot}*/usr/include/absl/flags/internal/usage.h
rm -f %{buildroot}*/usr/include/absl/flags/marshalling.h
rm -f %{buildroot}*/usr/include/absl/flags/parse.h
rm -f %{buildroot}*/usr/include/absl/flags/reflection.h
rm -f %{buildroot}*/usr/include/absl/flags/usage.h
rm -f %{buildroot}*/usr/include/absl/flags/usage_config.h
rm -f %{buildroot}*/usr/include/absl/functional/any_invocable.h
rm -f %{buildroot}*/usr/include/absl/functional/bind_front.h
rm -f %{buildroot}*/usr/include/absl/functional/function_ref.h
rm -f %{buildroot}*/usr/include/absl/functional/internal/any_invocable.h
rm -f %{buildroot}*/usr/include/absl/functional/internal/front_binder.h
rm -f %{buildroot}*/usr/include/absl/functional/internal/function_ref.h
rm -f %{buildroot}*/usr/include/absl/functional/overload.h
rm -f %{buildroot}*/usr/include/absl/hash/hash.h
rm -f %{buildroot}*/usr/include/absl/hash/hash_testing.h
rm -f %{buildroot}*/usr/include/absl/hash/internal/city.h
rm -f %{buildroot}*/usr/include/absl/hash/internal/hash.h
rm -f %{buildroot}*/usr/include/absl/hash/internal/hash_test.h
rm -f %{buildroot}*/usr/include/absl/hash/internal/low_level_hash.h
rm -f %{buildroot}*/usr/include/absl/hash/internal/spy_hash_state.h
rm -f %{buildroot}*/usr/include/absl/log/absl_check.h
rm -f %{buildroot}*/usr/include/absl/log/absl_log.h
rm -f %{buildroot}*/usr/include/absl/log/absl_vlog_is_on.h
rm -f %{buildroot}*/usr/include/absl/log/check.h
rm -f %{buildroot}*/usr/include/absl/log/check_test_impl.inc
rm -f %{buildroot}*/usr/include/absl/log/die_if_null.h
rm -f %{buildroot}*/usr/include/absl/log/flags.h
rm -f %{buildroot}*/usr/include/absl/log/globals.h
rm -f %{buildroot}*/usr/include/absl/log/initialize.h
rm -f %{buildroot}*/usr/include/absl/log/internal/append_truncated.h
rm -f %{buildroot}*/usr/include/absl/log/internal/check_impl.h
rm -f %{buildroot}*/usr/include/absl/log/internal/check_op.h
rm -f %{buildroot}*/usr/include/absl/log/internal/conditions.h
rm -f %{buildroot}*/usr/include/absl/log/internal/config.h
rm -f %{buildroot}*/usr/include/absl/log/internal/flags.h
rm -f %{buildroot}*/usr/include/absl/log/internal/fnmatch.h
rm -f %{buildroot}*/usr/include/absl/log/internal/globals.h
rm -f %{buildroot}*/usr/include/absl/log/internal/log_format.h
rm -f %{buildroot}*/usr/include/absl/log/internal/log_impl.h
rm -f %{buildroot}*/usr/include/absl/log/internal/log_message.h
rm -f %{buildroot}*/usr/include/absl/log/internal/log_sink_set.h
rm -f %{buildroot}*/usr/include/absl/log/internal/nullguard.h
rm -f %{buildroot}*/usr/include/absl/log/internal/nullstream.h
rm -f %{buildroot}*/usr/include/absl/log/internal/proto.h
rm -f %{buildroot}*/usr/include/absl/log/internal/strip.h
rm -f %{buildroot}*/usr/include/absl/log/internal/structured.h
rm -f %{buildroot}*/usr/include/absl/log/internal/test_actions.h
rm -f %{buildroot}*/usr/include/absl/log/internal/test_helpers.h
rm -f %{buildroot}*/usr/include/absl/log/internal/test_matchers.h
rm -f %{buildroot}*/usr/include/absl/log/internal/vlog_config.h
rm -f %{buildroot}*/usr/include/absl/log/internal/voidify.h
rm -f %{buildroot}*/usr/include/absl/log/log.h
rm -f %{buildroot}*/usr/include/absl/log/log_basic_test_impl.inc
rm -f %{buildroot}*/usr/include/absl/log/log_entry.h
rm -f %{buildroot}*/usr/include/absl/log/log_sink.h
rm -f %{buildroot}*/usr/include/absl/log/log_sink_registry.h
rm -f %{buildroot}*/usr/include/absl/log/log_streamer.h
rm -f %{buildroot}*/usr/include/absl/log/scoped_mock_log.h
rm -f %{buildroot}*/usr/include/absl/log/structured.h
rm -f %{buildroot}*/usr/include/absl/log/vlog_is_on.h
rm -f %{buildroot}*/usr/include/absl/memory/memory.h
rm -f %{buildroot}*/usr/include/absl/meta/type_traits.h
rm -f %{buildroot}*/usr/include/absl/numeric/bits.h
rm -f %{buildroot}*/usr/include/absl/numeric/int128.h
rm -f %{buildroot}*/usr/include/absl/numeric/int128_have_intrinsic.inc
rm -f %{buildroot}*/usr/include/absl/numeric/int128_no_intrinsic.inc
rm -f %{buildroot}*/usr/include/absl/numeric/internal/bits.h
rm -f %{buildroot}*/usr/include/absl/numeric/internal/representation.h
rm -f %{buildroot}*/usr/include/absl/profiling/internal/exponential_biased.h
rm -f %{buildroot}*/usr/include/absl/profiling/internal/periodic_sampler.h
rm -f %{buildroot}*/usr/include/absl/profiling/internal/sample_recorder.h
rm -f %{buildroot}*/usr/include/absl/random/bernoulli_distribution.h
rm -f %{buildroot}*/usr/include/absl/random/beta_distribution.h
rm -f %{buildroot}*/usr/include/absl/random/bit_gen_ref.h
rm -f %{buildroot}*/usr/include/absl/random/discrete_distribution.h
rm -f %{buildroot}*/usr/include/absl/random/distributions.h
rm -f %{buildroot}*/usr/include/absl/random/exponential_distribution.h
rm -f %{buildroot}*/usr/include/absl/random/gaussian_distribution.h
rm -f %{buildroot}*/usr/include/absl/random/internal/chi_square.h
rm -f %{buildroot}*/usr/include/absl/random/internal/distribution_caller.h
rm -f %{buildroot}*/usr/include/absl/random/internal/distribution_test_util.h
rm -f %{buildroot}*/usr/include/absl/random/internal/explicit_seed_seq.h
rm -f %{buildroot}*/usr/include/absl/random/internal/fast_uniform_bits.h
rm -f %{buildroot}*/usr/include/absl/random/internal/fastmath.h
rm -f %{buildroot}*/usr/include/absl/random/internal/generate_real.h
rm -f %{buildroot}*/usr/include/absl/random/internal/iostream_state_saver.h
rm -f %{buildroot}*/usr/include/absl/random/internal/mock_helpers.h
rm -f %{buildroot}*/usr/include/absl/random/internal/mock_overload_set.h
rm -f %{buildroot}*/usr/include/absl/random/internal/nanobenchmark.h
rm -f %{buildroot}*/usr/include/absl/random/internal/nonsecure_base.h
rm -f %{buildroot}*/usr/include/absl/random/internal/pcg_engine.h
rm -f %{buildroot}*/usr/include/absl/random/internal/platform.h
rm -f %{buildroot}*/usr/include/absl/random/internal/pool_urbg.h
rm -f %{buildroot}*/usr/include/absl/random/internal/randen.h
rm -f %{buildroot}*/usr/include/absl/random/internal/randen_detect.h
rm -f %{buildroot}*/usr/include/absl/random/internal/randen_engine.h
rm -f %{buildroot}*/usr/include/absl/random/internal/randen_hwaes.h
rm -f %{buildroot}*/usr/include/absl/random/internal/randen_slow.h
rm -f %{buildroot}*/usr/include/absl/random/internal/randen_traits.h
rm -f %{buildroot}*/usr/include/absl/random/internal/salted_seed_seq.h
rm -f %{buildroot}*/usr/include/absl/random/internal/seed_material.h
rm -f %{buildroot}*/usr/include/absl/random/internal/sequence_urbg.h
rm -f %{buildroot}*/usr/include/absl/random/internal/traits.h
rm -f %{buildroot}*/usr/include/absl/random/internal/uniform_helper.h
rm -f %{buildroot}*/usr/include/absl/random/internal/wide_multiply.h
rm -f %{buildroot}*/usr/include/absl/random/log_uniform_int_distribution.h
rm -f %{buildroot}*/usr/include/absl/random/mock_distributions.h
rm -f %{buildroot}*/usr/include/absl/random/mocking_bit_gen.h
rm -f %{buildroot}*/usr/include/absl/random/poisson_distribution.h
rm -f %{buildroot}*/usr/include/absl/random/random.h
rm -f %{buildroot}*/usr/include/absl/random/seed_gen_exception.h
rm -f %{buildroot}*/usr/include/absl/random/seed_sequences.h
rm -f %{buildroot}*/usr/include/absl/random/uniform_int_distribution.h
rm -f %{buildroot}*/usr/include/absl/random/uniform_real_distribution.h
rm -f %{buildroot}*/usr/include/absl/random/zipf_distribution.h
rm -f %{buildroot}*/usr/include/absl/status/internal/status_internal.h
rm -f %{buildroot}*/usr/include/absl/status/internal/statusor_internal.h
rm -f %{buildroot}*/usr/include/absl/status/status.h
rm -f %{buildroot}*/usr/include/absl/status/status_payload_printer.h
rm -f %{buildroot}*/usr/include/absl/status/statusor.h
rm -f %{buildroot}*/usr/include/absl/strings/ascii.h
rm -f %{buildroot}*/usr/include/absl/strings/charconv.h
rm -f %{buildroot}*/usr/include/absl/strings/charset.h
rm -f %{buildroot}*/usr/include/absl/strings/cord.h
rm -f %{buildroot}*/usr/include/absl/strings/cord_analysis.h
rm -f %{buildroot}*/usr/include/absl/strings/cord_buffer.h
rm -f %{buildroot}*/usr/include/absl/strings/cord_test_helpers.h
rm -f %{buildroot}*/usr/include/absl/strings/cordz_test_helpers.h
rm -f %{buildroot}*/usr/include/absl/strings/escaping.h
rm -f %{buildroot}*/usr/include/absl/strings/has_absl_stringify.h
rm -f %{buildroot}*/usr/include/absl/strings/has_ostream_operator.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/charconv_bigint.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/charconv_parse.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/cord_data_edge.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/cord_internal.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/cord_rep_btree.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/cord_rep_btree_navigator.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/cord_rep_btree_reader.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/cord_rep_consume.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/cord_rep_crc.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/cord_rep_flat.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/cord_rep_test_util.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/cordz_functions.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/cordz_handle.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/cordz_info.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/cordz_sample_token.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/cordz_statistics.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/cordz_update_scope.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/cordz_update_tracker.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/damerau_levenshtein_distance.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/escaping.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/escaping_test_common.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/has_absl_stringify.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/memutil.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/numbers_test_common.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/ostringstream.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/pow10_helper.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/resize_uninitialized.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/stl_type_traits.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/str_format/arg.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/str_format/bind.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/str_format/checker.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/str_format/constexpr_parser.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/str_format/extension.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/str_format/float_conversion.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/str_format/output.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/str_format/parser.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/str_join_internal.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/str_split_internal.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/string_constant.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/stringify_sink.h
rm -f %{buildroot}*/usr/include/absl/strings/internal/utf8.h
rm -f %{buildroot}*/usr/include/absl/strings/match.h
rm -f %{buildroot}*/usr/include/absl/strings/numbers.h
rm -f %{buildroot}*/usr/include/absl/strings/str_cat.h
rm -f %{buildroot}*/usr/include/absl/strings/str_format.h
rm -f %{buildroot}*/usr/include/absl/strings/str_join.h
rm -f %{buildroot}*/usr/include/absl/strings/str_replace.h
rm -f %{buildroot}*/usr/include/absl/strings/str_split.h
rm -f %{buildroot}*/usr/include/absl/strings/string_view.h
rm -f %{buildroot}*/usr/include/absl/strings/strip.h
rm -f %{buildroot}*/usr/include/absl/strings/substitute.h
rm -f %{buildroot}*/usr/include/absl/synchronization/barrier.h
rm -f %{buildroot}*/usr/include/absl/synchronization/blocking_counter.h
rm -f %{buildroot}*/usr/include/absl/synchronization/internal/create_thread_identity.h
rm -f %{buildroot}*/usr/include/absl/synchronization/internal/futex.h
rm -f %{buildroot}*/usr/include/absl/synchronization/internal/futex_waiter.h
rm -f %{buildroot}*/usr/include/absl/synchronization/internal/graphcycles.h
rm -f %{buildroot}*/usr/include/absl/synchronization/internal/kernel_timeout.h
rm -f %{buildroot}*/usr/include/absl/synchronization/internal/per_thread_sem.h
rm -f %{buildroot}*/usr/include/absl/synchronization/internal/pthread_waiter.h
rm -f %{buildroot}*/usr/include/absl/synchronization/internal/sem_waiter.h
rm -f %{buildroot}*/usr/include/absl/synchronization/internal/stdcpp_waiter.h
rm -f %{buildroot}*/usr/include/absl/synchronization/internal/thread_pool.h
rm -f %{buildroot}*/usr/include/absl/synchronization/internal/waiter.h
rm -f %{buildroot}*/usr/include/absl/synchronization/internal/waiter_base.h
rm -f %{buildroot}*/usr/include/absl/synchronization/internal/win32_waiter.h
rm -f %{buildroot}*/usr/include/absl/synchronization/mutex.h
rm -f %{buildroot}*/usr/include/absl/synchronization/notification.h
rm -f %{buildroot}*/usr/include/absl/time/civil_time.h
rm -f %{buildroot}*/usr/include/absl/time/clock.h
rm -f %{buildroot}*/usr/include/absl/time/internal/cctz/include/cctz/civil_time.h
rm -f %{buildroot}*/usr/include/absl/time/internal/cctz/include/cctz/civil_time_detail.h
rm -f %{buildroot}*/usr/include/absl/time/internal/cctz/include/cctz/time_zone.h
rm -f %{buildroot}*/usr/include/absl/time/internal/cctz/include/cctz/zone_info_source.h
rm -f %{buildroot}*/usr/include/absl/time/internal/cctz/src/time_zone_fixed.h
rm -f %{buildroot}*/usr/include/absl/time/internal/cctz/src/time_zone_if.h
rm -f %{buildroot}*/usr/include/absl/time/internal/cctz/src/time_zone_impl.h
rm -f %{buildroot}*/usr/include/absl/time/internal/cctz/src/time_zone_info.h
rm -f %{buildroot}*/usr/include/absl/time/internal/cctz/src/time_zone_libc.h
rm -f %{buildroot}*/usr/include/absl/time/internal/cctz/src/time_zone_posix.h
rm -f %{buildroot}*/usr/include/absl/time/internal/cctz/src/tzfile.h
rm -f %{buildroot}*/usr/include/absl/time/internal/get_current_time_chrono.inc
rm -f %{buildroot}*/usr/include/absl/time/internal/get_current_time_posix.inc
rm -f %{buildroot}*/usr/include/absl/time/internal/test_util.h
rm -f %{buildroot}*/usr/include/absl/time/time.h
rm -f %{buildroot}*/usr/include/absl/types/any.h
rm -f %{buildroot}*/usr/include/absl/types/bad_any_cast.h
rm -f %{buildroot}*/usr/include/absl/types/bad_optional_access.h
rm -f %{buildroot}*/usr/include/absl/types/bad_variant_access.h
rm -f %{buildroot}*/usr/include/absl/types/compare.h
rm -f %{buildroot}*/usr/include/absl/types/internal/optional.h
rm -f %{buildroot}*/usr/include/absl/types/internal/span.h
rm -f %{buildroot}*/usr/include/absl/types/internal/variant.h
rm -f %{buildroot}*/usr/include/absl/types/optional.h
rm -f %{buildroot}*/usr/include/absl/types/span.h
rm -f %{buildroot}*/usr/include/absl/types/variant.h
rm -f %{buildroot}*/usr/include/absl/utility/internal/if_constexpr.h
rm -f %{buildroot}*/usr/include/absl/utility/utility.h
rm -f %{buildroot}*/usr/lib64/cmake/absl/abslConfig.cmake
rm -f %{buildroot}*/usr/lib64/cmake/absl/abslConfigVersion.cmake
rm -f %{buildroot}*/usr/lib64/cmake/absl/abslTargets-relwithdebinfo.cmake
rm -f %{buildroot}*/usr/lib64/cmake/absl/abslTargets.cmake
rm -f %{buildroot}*/usr/lib64/libabsl_bad_any_cast_impl.so
rm -f %{buildroot}*/usr/lib64/libabsl_bad_optional_access.so
rm -f %{buildroot}*/usr/lib64/libabsl_bad_variant_access.so
rm -f %{buildroot}*/usr/lib64/libabsl_base.so
rm -f %{buildroot}*/usr/lib64/libabsl_city.so
rm -f %{buildroot}*/usr/lib64/libabsl_civil_time.so
rm -f %{buildroot}*/usr/lib64/libabsl_cord.so
rm -f %{buildroot}*/usr/lib64/libabsl_cord_internal.so
rm -f %{buildroot}*/usr/lib64/libabsl_cordz_functions.so
rm -f %{buildroot}*/usr/lib64/libabsl_cordz_handle.so
rm -f %{buildroot}*/usr/lib64/libabsl_cordz_info.so
rm -f %{buildroot}*/usr/lib64/libabsl_cordz_sample_token.so
rm -f %{buildroot}*/usr/lib64/libabsl_crc32c.so
rm -f %{buildroot}*/usr/lib64/libabsl_crc_cord_state.so
rm -f %{buildroot}*/usr/lib64/libabsl_crc_cpu_detect.so
rm -f %{buildroot}*/usr/lib64/libabsl_crc_internal.so
rm -f %{buildroot}*/usr/lib64/libabsl_debugging_internal.so
rm -f %{buildroot}*/usr/lib64/libabsl_demangle_internal.so
rm -f %{buildroot}*/usr/lib64/libabsl_die_if_null.so
rm -f %{buildroot}*/usr/lib64/libabsl_examine_stack.so
rm -f %{buildroot}*/usr/lib64/libabsl_exponential_biased.so
rm -f %{buildroot}*/usr/lib64/libabsl_failure_signal_handler.so
rm -f %{buildroot}*/usr/lib64/libabsl_flags_commandlineflag.so
rm -f %{buildroot}*/usr/lib64/libabsl_flags_commandlineflag_internal.so
rm -f %{buildroot}*/usr/lib64/libabsl_flags_config.so
rm -f %{buildroot}*/usr/lib64/libabsl_flags_internal.so
rm -f %{buildroot}*/usr/lib64/libabsl_flags_marshalling.so
rm -f %{buildroot}*/usr/lib64/libabsl_flags_parse.so
rm -f %{buildroot}*/usr/lib64/libabsl_flags_private_handle_accessor.so
rm -f %{buildroot}*/usr/lib64/libabsl_flags_program_name.so
rm -f %{buildroot}*/usr/lib64/libabsl_flags_reflection.so
rm -f %{buildroot}*/usr/lib64/libabsl_flags_usage.so
rm -f %{buildroot}*/usr/lib64/libabsl_flags_usage_internal.so
rm -f %{buildroot}*/usr/lib64/libabsl_graphcycles_internal.so
rm -f %{buildroot}*/usr/lib64/libabsl_hash.so
rm -f %{buildroot}*/usr/lib64/libabsl_hashtablez_sampler.so
rm -f %{buildroot}*/usr/lib64/libabsl_int128.so
rm -f %{buildroot}*/usr/lib64/libabsl_kernel_timeout_internal.so
rm -f %{buildroot}*/usr/lib64/libabsl_leak_check.so
rm -f %{buildroot}*/usr/lib64/libabsl_log_entry.so
rm -f %{buildroot}*/usr/lib64/libabsl_log_flags.so
rm -f %{buildroot}*/usr/lib64/libabsl_log_globals.so
rm -f %{buildroot}*/usr/lib64/libabsl_log_initialize.so
rm -f %{buildroot}*/usr/lib64/libabsl_log_internal_check_op.so
rm -f %{buildroot}*/usr/lib64/libabsl_log_internal_conditions.so
rm -f %{buildroot}*/usr/lib64/libabsl_log_internal_fnmatch.so
rm -f %{buildroot}*/usr/lib64/libabsl_log_internal_format.so
rm -f %{buildroot}*/usr/lib64/libabsl_log_internal_globals.so
rm -f %{buildroot}*/usr/lib64/libabsl_log_internal_log_sink_set.so
rm -f %{buildroot}*/usr/lib64/libabsl_log_internal_message.so
rm -f %{buildroot}*/usr/lib64/libabsl_log_internal_nullguard.so
rm -f %{buildroot}*/usr/lib64/libabsl_log_internal_proto.so
rm -f %{buildroot}*/usr/lib64/libabsl_log_severity.so
rm -f %{buildroot}*/usr/lib64/libabsl_log_sink.so
rm -f %{buildroot}*/usr/lib64/libabsl_low_level_hash.so
rm -f %{buildroot}*/usr/lib64/libabsl_malloc_internal.so
rm -f %{buildroot}*/usr/lib64/libabsl_periodic_sampler.so
rm -f %{buildroot}*/usr/lib64/libabsl_random_distributions.so
rm -f %{buildroot}*/usr/lib64/libabsl_random_internal_distribution_test_util.so
rm -f %{buildroot}*/usr/lib64/libabsl_random_internal_platform.so
rm -f %{buildroot}*/usr/lib64/libabsl_random_internal_pool_urbg.so
rm -f %{buildroot}*/usr/lib64/libabsl_random_internal_randen.so
rm -f %{buildroot}*/usr/lib64/libabsl_random_internal_randen_hwaes.so
rm -f %{buildroot}*/usr/lib64/libabsl_random_internal_randen_hwaes_impl.so
rm -f %{buildroot}*/usr/lib64/libabsl_random_internal_randen_slow.so
rm -f %{buildroot}*/usr/lib64/libabsl_random_internal_seed_material.so
rm -f %{buildroot}*/usr/lib64/libabsl_random_seed_gen_exception.so
rm -f %{buildroot}*/usr/lib64/libabsl_random_seed_sequences.so
rm -f %{buildroot}*/usr/lib64/libabsl_raw_hash_set.so
rm -f %{buildroot}*/usr/lib64/libabsl_raw_logging_internal.so
rm -f %{buildroot}*/usr/lib64/libabsl_scoped_mock_log.so
rm -f %{buildroot}*/usr/lib64/libabsl_scoped_set_env.so
rm -f %{buildroot}*/usr/lib64/libabsl_spinlock_wait.so
rm -f %{buildroot}*/usr/lib64/libabsl_stacktrace.so
rm -f %{buildroot}*/usr/lib64/libabsl_status.so
rm -f %{buildroot}*/usr/lib64/libabsl_statusor.so
rm -f %{buildroot}*/usr/lib64/libabsl_str_format_internal.so
rm -f %{buildroot}*/usr/lib64/libabsl_strerror.so
rm -f %{buildroot}*/usr/lib64/libabsl_string_view.so
rm -f %{buildroot}*/usr/lib64/libabsl_strings.so
rm -f %{buildroot}*/usr/lib64/libabsl_strings_internal.so
rm -f %{buildroot}*/usr/lib64/libabsl_symbolize.so
rm -f %{buildroot}*/usr/lib64/libabsl_synchronization.so
rm -f %{buildroot}*/usr/lib64/libabsl_throw_delegate.so
rm -f %{buildroot}*/usr/lib64/libabsl_time.so
rm -f %{buildroot}*/usr/lib64/libabsl_time_zone.so
rm -f %{buildroot}*/usr/lib64/libabsl_vlog_config_internal.so
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_absl_check.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_absl_log.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_absl_vlog_is_on.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_algorithm.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_algorithm_container.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_any.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_any_invocable.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_atomic_hook.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_bad_any_cast.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_bad_any_cast_impl.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_bad_optional_access.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_bad_variant_access.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_base.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_base_internal.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_bind_front.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_bits.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_btree.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_charset.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_check.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_city.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_civil_time.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_cleanup.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_cleanup_internal.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_common_policy_traits.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_compare.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_compressed_tuple.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_config.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_container_common.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_container_memory.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_cord.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_cord_internal.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_cord_test_helpers.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_cordz_functions.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_cordz_handle.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_cordz_info.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_cordz_sample_token.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_cordz_statistics.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_cordz_update_scope.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_cordz_update_tracker.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_core_headers.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_crc32c.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_crc_cord_state.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_crc_cpu_detect.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_crc_internal.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_debugging.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_debugging_internal.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_demangle_internal.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_die_if_null.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_dynamic_annotations.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_endian.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_errno_saver.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_examine_stack.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_exponential_biased.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_failure_signal_handler.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_fast_type_id.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_fixed_array.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_flags.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_flags_commandlineflag.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_flags_commandlineflag_internal.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_flags_config.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_flags_internal.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_flags_marshalling.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_flags_parse.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_flags_path_util.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_flags_private_handle_accessor.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_flags_program_name.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_flags_reflection.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_flags_usage.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_flags_usage_internal.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_flat_hash_map.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_flat_hash_set.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_function_ref.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_graphcycles_internal.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_has_ostream_operator.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_hash.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_hash_function_defaults.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_hash_policy_traits.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_hash_testing.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_hashtable_debug.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_hashtable_debug_hooks.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_hashtablez_sampler.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_if_constexpr.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_inlined_vector.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_inlined_vector_internal.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_int128.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_kernel_timeout_internal.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_layout.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_leak_check.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_log.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_log_entry.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_log_flags.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_log_globals.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_log_initialize.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_log_internal_append_truncated.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_log_internal_check_impl.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_log_internal_check_op.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_log_internal_conditions.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_log_internal_config.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_log_internal_flags.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_log_internal_fnmatch.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_log_internal_format.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_log_internal_globals.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_log_internal_log_impl.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_log_internal_log_sink_set.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_log_internal_message.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_log_internal_nullguard.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_log_internal_nullstream.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_log_internal_proto.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_log_internal_strip.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_log_internal_structured.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_log_internal_voidify.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_log_severity.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_log_sink.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_log_sink_registry.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_log_streamer.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_log_structured.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_low_level_hash.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_malloc_internal.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_memory.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_meta.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_no_destructor.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_node_hash_map.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_node_hash_set.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_node_slot_policy.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_non_temporal_arm_intrinsics.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_non_temporal_memcpy.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_nullability.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_numeric.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_numeric_representation.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_optional.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_overload.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_periodic_sampler.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_prefetch.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_pretty_function.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_random_bit_gen_ref.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_random_distributions.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_random_internal_distribution_caller.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_random_internal_distribution_test_util.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_random_internal_fast_uniform_bits.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_random_internal_fastmath.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_random_internal_generate_real.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_random_internal_iostream_state_saver.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_random_internal_mock_helpers.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_random_internal_nonsecure_base.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_random_internal_pcg_engine.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_random_internal_platform.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_random_internal_pool_urbg.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_random_internal_randen.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_random_internal_randen_engine.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_random_internal_randen_hwaes.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_random_internal_randen_hwaes_impl.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_random_internal_randen_slow.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_random_internal_salted_seed_seq.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_random_internal_seed_material.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_random_internal_traits.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_random_internal_uniform_helper.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_random_internal_wide_multiply.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_random_mocking_bit_gen.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_random_random.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_random_seed_gen_exception.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_random_seed_sequences.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_raw_hash_map.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_raw_hash_set.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_raw_logging_internal.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_sample_recorder.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_scoped_mock_log.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_scoped_set_env.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_span.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_spinlock_wait.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_spy_hash_state.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_stacktrace.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_status.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_statusor.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_str_format.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_str_format_internal.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_strerror.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_string_view.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_strings.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_strings_internal.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_symbolize.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_synchronization.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_test_allocator.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_throw_delegate.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_time.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_time_zone.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_type_traits.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_utility.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_variant.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_vlog_config_internal.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/absl_vlog_is_on.pc

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/libabsl_bad_any_cast_impl.so.2401.0.0
/usr/lib64/libabsl_bad_optional_access.so.2401.0.0
/usr/lib64/libabsl_bad_variant_access.so.2401.0.0
/usr/lib64/libabsl_base.so.2401.0.0
/usr/lib64/libabsl_city.so.2401.0.0
/usr/lib64/libabsl_civil_time.so.2401.0.0
/usr/lib64/libabsl_cord.so.2401.0.0
/usr/lib64/libabsl_cord_internal.so.2401.0.0
/usr/lib64/libabsl_cordz_functions.so.2401.0.0
/usr/lib64/libabsl_cordz_handle.so.2401.0.0
/usr/lib64/libabsl_cordz_info.so.2401.0.0
/usr/lib64/libabsl_cordz_sample_token.so.2401.0.0
/usr/lib64/libabsl_crc32c.so.2401.0.0
/usr/lib64/libabsl_crc_cord_state.so.2401.0.0
/usr/lib64/libabsl_crc_cpu_detect.so.2401.0.0
/usr/lib64/libabsl_crc_internal.so.2401.0.0
/usr/lib64/libabsl_debugging_internal.so.2401.0.0
/usr/lib64/libabsl_demangle_internal.so.2401.0.0
/usr/lib64/libabsl_die_if_null.so.2401.0.0
/usr/lib64/libabsl_examine_stack.so.2401.0.0
/usr/lib64/libabsl_exponential_biased.so.2401.0.0
/usr/lib64/libabsl_failure_signal_handler.so.2401.0.0
/usr/lib64/libabsl_flags_commandlineflag.so.2401.0.0
/usr/lib64/libabsl_flags_commandlineflag_internal.so.2401.0.0
/usr/lib64/libabsl_flags_config.so.2401.0.0
/usr/lib64/libabsl_flags_internal.so.2401.0.0
/usr/lib64/libabsl_flags_marshalling.so.2401.0.0
/usr/lib64/libabsl_flags_parse.so.2401.0.0
/usr/lib64/libabsl_flags_private_handle_accessor.so.2401.0.0
/usr/lib64/libabsl_flags_program_name.so.2401.0.0
/usr/lib64/libabsl_flags_reflection.so.2401.0.0
/usr/lib64/libabsl_flags_usage.so.2401.0.0
/usr/lib64/libabsl_flags_usage_internal.so.2401.0.0
/usr/lib64/libabsl_graphcycles_internal.so.2401.0.0
/usr/lib64/libabsl_hash.so.2401.0.0
/usr/lib64/libabsl_hashtablez_sampler.so.2401.0.0
/usr/lib64/libabsl_int128.so.2401.0.0
/usr/lib64/libabsl_kernel_timeout_internal.so.2401.0.0
/usr/lib64/libabsl_leak_check.so.2401.0.0
/usr/lib64/libabsl_log_entry.so.2401.0.0
/usr/lib64/libabsl_log_flags.so.2401.0.0
/usr/lib64/libabsl_log_globals.so.2401.0.0
/usr/lib64/libabsl_log_initialize.so.2401.0.0
/usr/lib64/libabsl_log_internal_check_op.so.2401.0.0
/usr/lib64/libabsl_log_internal_conditions.so.2401.0.0
/usr/lib64/libabsl_log_internal_fnmatch.so.2401.0.0
/usr/lib64/libabsl_log_internal_format.so.2401.0.0
/usr/lib64/libabsl_log_internal_globals.so.2401.0.0
/usr/lib64/libabsl_log_internal_log_sink_set.so.2401.0.0
/usr/lib64/libabsl_log_internal_message.so.2401.0.0
/usr/lib64/libabsl_log_internal_nullguard.so.2401.0.0
/usr/lib64/libabsl_log_internal_proto.so.2401.0.0
/usr/lib64/libabsl_log_severity.so.2401.0.0
/usr/lib64/libabsl_log_sink.so.2401.0.0
/usr/lib64/libabsl_low_level_hash.so.2401.0.0
/usr/lib64/libabsl_malloc_internal.so.2401.0.0
/usr/lib64/libabsl_periodic_sampler.so.2401.0.0
/usr/lib64/libabsl_random_distributions.so.2401.0.0
/usr/lib64/libabsl_random_internal_distribution_test_util.so.2401.0.0
/usr/lib64/libabsl_random_internal_platform.so.2401.0.0
/usr/lib64/libabsl_random_internal_pool_urbg.so.2401.0.0
/usr/lib64/libabsl_random_internal_randen.so.2401.0.0
/usr/lib64/libabsl_random_internal_randen_hwaes.so.2401.0.0
/usr/lib64/libabsl_random_internal_randen_hwaes_impl.so.2401.0.0
/usr/lib64/libabsl_random_internal_randen_slow.so.2401.0.0
/usr/lib64/libabsl_random_internal_seed_material.so.2401.0.0
/usr/lib64/libabsl_random_seed_gen_exception.so.2401.0.0
/usr/lib64/libabsl_random_seed_sequences.so.2401.0.0
/usr/lib64/libabsl_raw_hash_set.so.2401.0.0
/usr/lib64/libabsl_raw_logging_internal.so.2401.0.0
/usr/lib64/libabsl_scoped_mock_log.so.2401.0.0
/usr/lib64/libabsl_scoped_set_env.so.2401.0.0
/usr/lib64/libabsl_spinlock_wait.so.2401.0.0
/usr/lib64/libabsl_stacktrace.so.2401.0.0
/usr/lib64/libabsl_status.so.2401.0.0
/usr/lib64/libabsl_statusor.so.2401.0.0
/usr/lib64/libabsl_str_format_internal.so.2401.0.0
/usr/lib64/libabsl_strerror.so.2401.0.0
/usr/lib64/libabsl_string_view.so.2401.0.0
/usr/lib64/libabsl_strings.so.2401.0.0
/usr/lib64/libabsl_strings_internal.so.2401.0.0
/usr/lib64/libabsl_symbolize.so.2401.0.0
/usr/lib64/libabsl_synchronization.so.2401.0.0
/usr/lib64/libabsl_throw_delegate.so.2401.0.0
/usr/lib64/libabsl_time.so.2401.0.0
/usr/lib64/libabsl_time_zone.so.2401.0.0
/usr/lib64/libabsl_vlog_config_internal.so.2401.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-abseil-cpp-rolling/77ca6ddbb42e1c1c589a0874f0ad28b7da4cccbb
